version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  confusion:
    image: lparisot/confusion
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/dishes"]
      interval: 30s
      timeout: 300s
      retries: 2
